### ISSUE TITLE
TLD permutation issue

### ISSUE THREAD

**Issue by tsellers-r7** [darkoperator/dnsrecon#103]
I don't think the following code behaves as expected.

https://github.com/darkoperator/dnsrecon/blob/d5636e7dc499f3793288b5401f6c6147f8d9af9b/dnsrecon.py#L307-L321

I think that lines 313 to 316 should be indented (the value of `t` never changes) and perhaps have the order of `cc` and `t` in the string construction reversed.   As it is, it will currently loop over domain name + country code + the last value in `stld` which is currently `.travel`.

Example output:
```
[*] Trying sammich.fr.travel
[*] Trying sammich.ga.travel
[*] Trying sammich.gb.travel
[*] Trying sammich.gd.travel
[*] Trying sammich.ge.travel
[*] Trying sammich.gf.travel
[*] Trying sammich.gg.travel
[*] Trying sammich.gh.travel
[*] Trying sammich.gi.travel
[*] Trying sammich.gl.travel
[*] Trying sammich.gm.travel
[*] Trying sammich.gn.travel
[*] Trying sammich.gp.travel
```

It will never loop over any other `stld` values due to the current indention.

I'd be happy to submit a PR if you wish. Just let me know the desired loop pattern.

**Comment by tsellers-r7** [comment]
Noticed while working on https://github.com/darkoperator/dnsrecon/pull/102

**Comment by tsellers-r7** [comment]
Reference list from Mozilla on common country specific domains
https://publicsuffix.org/list/effective_tld_names.dat

**Comment by darkoperator** [comment]
Yep place it with the last PR

**Comment by tsellers-r7** [comment]
Will do. I'm having to rework how wildcard detection is done because it appears that many of the country code tlds and some others have wildcard resolution enabled. I have most of that sorted out but there is some subtle bug where a couple are still making it through
