### ISSUE TITLE
Subdomain brute force list

### ISSUE THREAD

**Issue by ethicalhack3r** [darkoperator/dnsrecon#11]
Was wondering if you might want to use one of the subdomain lists I created from the Alexa Top 1 Million sites AXFR results - http://www.ethicalhack3r.co.uk/zone-transfers-on-the-alexa-top-1-million-part-2/

**Comment by PeterDaveHello** [comment]
Alexa is going to shutdown, and it's been 8 years since the first time the subdomain brute force list created, not sure if the list should be updated again before the shutdown, or should simply be removed?

Reference: https://support.alexa.com/hc/en-us/articles/4410503838999
