### ISSUE TITLE
No way to specify "bruteforce mode" via an individual parameter

### ISSUE THREAD

**Issue by TAbdiukov** [darkoperator/dnsrecon#112]
All other options (Google, Bing, zonewalk etc) seem to be specifiable via both `-t (mode)` and `--indivial_mode`. All, except bruteforce. I wonder if this is intentional, given that on many machines, the `-t` sub-options aren't being displayed, likely due to the padding

**Comment by L1ghtn1ng** [comment]
This still the case with the code in master?

**Comment by L1ghtn1ng** [comment]
You do this with the -t brt
