### ISSUE TITLE
Force name server

### ISSUE THREAD

**Issue by elbae** [darkoperator/dnsrecon#113]
Hello, this might not be the best place, but I am facing a problem.
I would like to specify the name server to "attack" in such a way that only the specified server would be targeted.
By looking at the -h option the following is written:
> -n, --name_server <name>     Domain server to use. If none is given, the SOA of the target will be used.

I thought that -n was ignoring SOA but I was wrong.

**Comment by darkoperator** [comment]
It will still enumerate using that name server the SOA an queries should be performed against the name server specified. Are you saying it is switching to the SOA for all other queries?

**Comment by elbae** [comment]
I'm probably wrong in the first comment.
Nevertheless I would like to know if it is possible to force the (-d choosen) .26 name server and ignore the (other/others) .132 one.

![image](https://user-images.githubusercontent.com/19212922/72903003-be5f6680-3d2c-11ea-9f25-2a960ee24e3f.png)

**Comment by darkoperator** [comment]
Zone Transfer check will be done against all NS records found. There is no way to single target it. The resolving if NS records is just that it asked .26 what NS records are in its DB and listed them.

**Comment by elbae** [comment]
Thank you for the clarification.
