### ISSUE TITLE
Switch to Python 3

### ISSUE THREAD

**Issue by rhertzog** [darkoperator/dnsrecon#115]
Python 2 is unsupported upstream. Thus dnsrecon should work with Python 3 and the shebangs should point to "python3" by default to ensure users are using Python 3 too. A couple of changes have already been made for Python 3 support but a quick test reveals that there are issues left to be fixed, and several of them are caught/fixed by running 2to3 on the codebase.

Among the things that I spotted:
- usage of "unicode()" function
- lack of parenthesis in a print statement in tools/parser.py (`print elem.attrib['address']`)
- usage of reader.next() vs next(reader) (for csv.reader object in tools/parser.py)
- usage of iteritems() in dnsrecon.py

**Comment by rhertzog** [comment]
BTW, this bug has been opened in response to the Debian bug https://bugs.debian.org/939641 since Debian is getting rid of Python 2 code everywhere.

**Comment by L1ghtn1ng** [comment]
This has been resolved in master
