### ISSUE TITLE
Zone Transfer results not displayed properly

### ISSUE THREAD

**Issue by ictbum** [darkoperator/dnsrecon#121]
Recently when working labs for the OSCP I encountered an issue performing a zone transfer with dnsrecon. Syntax used was "dnsrecon -t axfr -d megacorpone.com". ns2.megacorpone.com is vulnerable to a zone transfer. Results are shown below. The odd thing is that the zone transfer does actually work as confirmed with the wireshark output below. Not sure why the results are not being parsed properly. I attempted the zone transfer with v0.9.0 and v0.10.0 and received the same results.
![axfr_fail](https://user-images.githubusercontent.com/63015511/78175438-7e012080-7420-11ea-8a75-5df574f03113.png)
![axfr_wireshark](https://user-images.githubusercontent.com/63015511/78175468-8d806980-7420-11ea-9ec3-8f053781b371.png)

**Comment by NotoriousRebel** [comment]
Thank you for raising this issue, this has been fixed in #120

**Comment by NotoriousRebel** [comment]
@ictbum Could you try with the latest version of the tool and let me know if the error is still there?

**Comment by ictbum** [comment]
Just checked and it does display the results properly now. Thanks for the quick action.
