### ISSUE TITLE
Ability to change DNS port

### ISSUE THREAD

**Issue by exander77** [darkoperator/dnsrecon#125]
Does not seem to be easily available in the program. Tried modifying dnshelper, no luck so far.

**Comment by NotoriousRebel** [comment]
Have you tried changing the global variable dnshelper as well as the port? https://github.com/darkoperator/dnsrecon/blob/8469a4473c3939bf189447a126fe6270292bcf8b/lib/dnshelper.py#L80

**Comment by L1ghtn1ng** [comment]
timeout
