### ISSUE TITLE
[Bug] -t std causing errors in general_enum

### ISSUE THREAD

**Issue by CriticalSecurity** [darkoperator/dnsrecon#131]
When using the -t std flag dnsrecon fails with a TypeError.

**To Reproduce**
1. Run tool like this: 'dnsrecon -d google.com -t std'
2. Error:

Traceback (most recent call last):
  File "./dnsrecon.py", line 1759, in <module>
    main()
  File "./dnsrecon.py", line 1577, in main
    std_enum_records = general_enum(res, domain, xfr, goo, bing, spf_enum, do_whois, do_crt, zonewalk,
  File "./dnsrecon.py", line 1030, in general_enum
    ip_for_whois.append(r["address"])
TypeError: list indices must be integers or slices, not str

**Expected behavior**
It is expected that the application completes and does not fail.

**System Information (System that tool is running on):**
 - OS: Kali Linux
 - Version [5.6.0-kali1-amd64 #1 SMP Debian 5.6.7-1kali1 (2020-05-12) x86_64 GNU/Linux]

**Additional context**
Dnsrecon was installed using the Kail repo "apt install dnsrecon". I ran "apt update && apt dist-upgrade" on May 19, 2020 and then these errors started.

Package: dnsrecon
Version: 0.9.1+git20200409-1
Priority: optional
Section: net
Maintainer: Debian Security Tools <team+pkg-security@tracker.debian.org>
Installed-Size: 1,482 kB
Depends: python3:any, python3-dnspython, python3-netaddr, python3-lxml
Homepage: https://github.com/darkoperator/dnsrecon
Download-Size: 472 kB
APT-Manual-Installed: no
APT-Sources: http://http.kali.org/kali kali-rolling/main amd64 Packages

The results are the same if using a cloned version from git. (0.10.0)

**Comment by CriticalSecurity** [comment]
Replacing the apt installed version with a git clone does not produce this errors.

**Comment by L1ghtn1ng** [comment]
Thanks for the report, will be looked into

**Comment by L1ghtn1ng** [comment]
If I use the kali version I can reproduce it but when using the git version with a virtualenv I cannot and it works fine. Can you try running the git version in a virtualenv and see what haapens?

**Comment by CriticalSecurity** [comment]
So I do experience the same as you, just using the git version and as a docker image, it works as expected. It just seems to be with the Kali version. Personally, for what I'm doing, I'm just going to abandon the kali version and use docker.

**Comment by L1ghtn1ng** [comment]
Fair enough, when there is a tagged release hopefully this should then be fixed in Kali as well
________________________________
