### ISSUE TITLE
AttributeError: module 'urllib' has no attribute 'urlopen'. I tried urllib.request.urlopen, but another AttributeError showed. Any fixes?

### ISSUE THREAD

**Issue by sisixs** [darkoperator/dnsrecon#132]
`import urllib
from bs4 import BeautifulSoup

#url = 'http://python-data.dr-chuck.net/known_by_Austin.html'
url = input('Enter URL:')
count = int(input('Enter count:'))
position = int(input('Enter position:'))-1
html = urllib.urlopen(url).read()
#problem is here.
soup = BeautifulSoup(html,"html.parser")
href = soup('a')
#print href

for i in range(count):
    link = href[position].get('href', None)
    print (href[position].contents[0])
    html = urllib.urlopen(link).read()
    soup = BeautifulSoup(html,"html.parser")
    href = soup('a')
input()
`

**Comment by L1ghtn1ng** [comment]
Timeout
