### ISSUE TITLE
[Bug] Zone Transfer Returns TypeError

### ISSUE THREAD

**Issue by bennettwarner** [darkoperator/dnsrecon#133]
**Feature Request or Bug or Other**
Bug

**Describe the feature request or bug or other**
When attempting a to use the -a flag (Perform AXFR with standard enumeration.) the error "TypeError: 'NoneType' object is not iterable" is returned.

**To Reproduce**
1. Run: python dnsrecon.py -a -n nsztm1.digi.ninja -d zonetransfer.me

<img width="524" alt="Screen Shot 2020-06-11 at 10 45 12 AM" src="https://user-images.githubusercontent.com/17283318/84401037-c97a3c80-abd0-11ea-96d1-8d9ca2928d34.png">

**System Information (System that tool is running on):**
 - OS: MacOS
 - Version Python 3.8

**Comment by L1ghtn1ng** [comment]
Have managed to reproduce it, thanks will have a look

**Comment by L1ghtn1ng** [comment]
@bennettwarner what happens if you remove the -n flag does it work then?

**Comment by bennettwarner** [comment]
Yes, it does run as intended without the -n flag. 
Guess it was a PEBKAC error. Thanks!
