### ISSUE TITLE
Filter -f not working with bruteforce and wildcard set

### ISSUE THREAD

**Issue by RobbertDongIt** [darkoperator/dnsrecon#134]
**Bug**

I am trying to probe a domain with a wildcard set.

I also set the -f flag, but it does not seem to work.

When I look at the code, I think the problem is within the 'get_a (in lib/dnshelper.py) function.
It does not always return just an A record.

So when it comes to comparing against this address, it fails (sometimes).
I cannot find many people with the same issue, so maybe I am wrong.
But i tried against 2 different domains with wildcards set and both with the same problems.

**To Reproduce**

Running from my Kali box:
```dnsrecon -d somedomain.com -t brt -D /some/name/list.txt -f -v --iw```

**Comment by RobbertDongIt** [comment]
I found issue #15:
" if the domain is set with a wildcard as a A or AAAA it should work unless a CNAME was used."

The domain I was testing used a CNAME, so that explains why it is not filtering.

But then, why should the filtering not be done/working is a CNAME is used?

Cheers, Robbert

**Comment by L1ghtn1ng** [comment]
@darkoperator can you comment on this please?

**Comment by L1ghtn1ng** [comment]
@RobbertDongIt Can you try and see if you get this issue with the new changes in git please?

**Comment by L1ghtn1ng** [comment]
Timeout
