### ISSUE TITLE
cert.sh enumeration broke

### ISSUE THREAD

**Issue by rewiaca** [darkoperator/dnsrecon#137]
```
./dnsrecon.py line 1030 in general_enum
ip_for_whois.append(r["adddres"])
TypeError: list indices must be integers or slice, not str
```

In newest version of dnsrecon I don't see -k arg in help
Is it deprecated function?

**Comment by L1ghtn1ng** [comment]
It is there and no it is not deprecated -h and you should see it
________________________________

**Comment by L1ghtn1ng** [comment]
Timeout
