### ISSUE TITLE
key error in check_bindversion which causes an error in program execution.

### ISSUE THREAD

**Issue by fantasticpanthom** [darkoperator/dnsrecon#143]
**Bug**
key error in check_bindversion which causes an error in program execution.

print_status(f"\t Bind Version for {ns_server} {response.answer[0].items[0].strings[0]}") in check_bindversion throws an key error which stops the execution of program.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the command  
```bash
python3 dnsrecon.py -d uber.com
```
>I have tried running the command with the domains example.com , google.com and uber.com
2. Error thrown
```
Traceback (most recent call last):
  File "dnsrecon.py", line 1671, in <module>
    main()
  File "dnsrecon.py", line 1631, in main
    std_enum_records = general_enum(res, domain, xfr, bing, spf_enum, do_whois, do_crt, zonewalk)
  File "dnsrecon.py", line 943, in general_enum
    bind_ver = check_bindversion(res, ns_rcrd[2], res._res.timeout)
  File "dnsrecon.py", line 856, in check_bindversion
    print_status(f"\t Bind Version for {ns_server} {response.answer[0].items[0].strings[0]}")
KeyError: 0
```

<img width="1280" alt="Screenshot 2020-10-17 at 8 15 15 PM" src="https://user-images.githubusercontent.com/45918807/96339953-7a2fa580-10b5-11eb-9b2f-0ab690099096.png">

**System Information :**
 - OS: macOS catalina
 - Version 10.15.5
 - Python : python3
 -Version 3.8.5

**Comment by L1ghtn1ng** [comment]
To fix this issue use the command switch that disables the bind check
which should do the trick

**Comment by L1ghtn1ng** [comment]
This has been fixed in master
