### ISSUE TITLE
DNS enumeration doesn't work

### ISSUE THREAD

**Issue by gmalets** [darkoperator/dnsrecon#148]
Bug 

I'm trying to play with dnsrecon on fresh updated kali 2020.04 and sometimes got errors.

Steps to reproduce the behaviour:
1. Run tool like this: 
dnsrecon -d fubsybox.com
dnsrecon -d agrotender.com.ua
dnsrecon -d mail.ru

2. See error
```
[*] Performing General Enumeration of Domain: fubsybox.com
[-] DNSSEC is not configured for fubsybox.com
[*]      NS ns2.time4vps.com 162.159.25.54
Traceback (most recent call last):
  File "./dnsrecon.py", line 1691, in <module>
    main()
  File "./dnsrecon.py", line 1651, in main
    std_enum_records = general_enum(res, domain, xfr, bing, yandex, spf_enum, do_whois, do_crt, zonewalk)
  File "./dnsrecon.py", line 934, in general_enum
    bind_ver = check_bindversion(res, ns_rcrd[2], res._res.timeout)
  File "./dnsrecon.py", line 847, in check_bindversion
    print_status(f"\t Bind Version for {ns_server} {response.answer[0].items[0].strings[0]}")
KeyError: 0
```

but if i try for example:
dnsrecon -d kali.org
dnsrecon -d microsoft.com
it works fine

**System Information (System that tool is running on):**
 - OS: Kali Linux
 - Version 2020.04
 - Version of dnsrecon: 0.9.1+git20200921-1
 - APT-Sources: http://http.kali.org/kali kali-rolling/main amd64 Packages

**Comment by tehpr0** [comment]
Also with the same reproduceable issue

![image](https://user-images.githubusercontent.com/5042600/101073256-12ff7f00-3597-11eb-8f34-d302047798fd.png)

**Comment by NorthShad0w** [comment]
it seems that the zonetransfer module has some problems.

**Comment by darkoperator** [comment]
Yep looking in to it. 
>

**Comment by FredrikAugust** [comment]
Same here.

**Comment by pr0xylien** [comment]
use dnsrecon -d domain.com --disable_check_bindversion

**Comment by L1ghtn1ng** [comment]
We are going to disable the bind check by default and make it optional, this should resolve the issue

**Comment by L1ghtn1ng** [comment]
This seems to be fixed as I cannot replicate it now with the latest git changes
