### ISSUE TITLE
setup.py: namelist.txt is not getting installed

### ISSUE THREAD

**Issue by blshkv** [darkoperator/dnsrecon#165]
you need patch, somelike like this: https://github.com/pentoo/pentoo-overlay/tree/master/net-analyzer/dnsrecon/files

**Comment by blshkv** [comment]
also, main binaires are not getting installed:
```
/usr/bin/dnsrecon
/usr/bin/dnsrecon-parser
```

**Comment by L1ghtn1ng** [comment]
Can you please check my PR to see if you are happy with it, dnsrecon-parser needs refactoring so will leave that out for now

**Comment by blshkv** [comment]
I have not tested it, but changes looks good. Thanks 👍
