### ISSUE TITLE
CSV and sqlite output aren't written to disk

### ISSUE THREAD

**Issue by emory** [darkoperator/dnsrecon#173]
Bug

This may be related to #130 — if I use flags for CSV output `-c netname.csv` or database output `--db localnet.db` the files are created but not populated with any of the output that is shown to stdout. My workaround is directing output to a file and then hacking it together with a couple of scripts to get what I'm looking for, but I'd love it if the CSV and database output worked as intended. I've used three workstations with the same result but they're all macOS using python3 via homebrew.

It hadn't occured to me to try on a GNU/linux system but I don't know why that would matter except for the way python might be packaged by debian/canonical/rhel vs homebrew packages.

```
❯ python3 dnsrecon.py -c 153net.csv -n 192.168.153.5 -r 192.168.153.0-192.168.153.255
[*] Reverse Look-up of a Range
[*] Performing Reverse Lookup from 192.168.153.0 to 192.168.153.255
…
[+] 38 Records Found
[*] Saving records to CSV file: 153net.csv

❯ cat 153net.csv
Type,Name,Address,Target,Port,String

❯
```

edit: I cloned the repository on one of my raspis in the house, installed the required packages via `pip3` and the same behavior happens.

**Comment by emory** [comment]
ah hell, I get an error message about the database output. Should I open that as a separate issue? The error I get:

```
[*] Saving records to SQLite3 file: 153net.db
Traceback (most recent call last):
  File "./dnsrecon.py", line 1714, in <module>
    main()
  File "./dnsrecon.py", line 1656, in main
    write_db(results_db, returned_records)
  File "./dnsrecon.py", line 759, in write_db
    if re.match(r'PTR|^[A]$|AAAA', n['type']):
TypeError: list indices must be integers or slices, not str
```

I didn't remember seeing an error before about sqlite 🤦

**Comment by L1ghtn1ng** [comment]
What version are you running?
________________________________

**Comment by emory** [comment]
all the things:

```
emory@raspi03 ~/pihome/Projects/dnsrecon % python3 dnsrecon.py -V
0.10.0
emory@raspi03 ~/pihome/Projects/dnsrecon % python3 --version
Python 3.7.3
emory@raspi03 ~/pihome/Projects/dnsrecon % uname -a
Linux raspi03 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 GNU/Linux
```

**Comment by emory** [comment]
I read some other issues, in case it was related I passed `--disable_check_bindversion` to it but it doesn't impact the behavior of CSV output or sqlite output on macOS or one of the raspis.

**Comment by emory** [comment]
I installed a new Kali VM and the dnsrecon included in Kali Linux doesn't write csv/database/json either, `head dnsrecon.py` on `/usr/share/dnsrecon/dnsrecon.py` says it's also version 0.10.0 but the `-V` flag doesn't work. It also demands I pass it `-d` when when I tell it `-r 192.168.1.0/24`. 

Does `dnsrecon` write sqlite databases/csv/json for anyone?

**Comment by L1ghtn1ng** [comment]
This should be fixed in master now
