### ISSUE TITLE
Dnsrecon too is not running showing name error

### ISSUE THREAD

**Issue by Sharmitanmay** [darkoperator/dnsrecon#191]
![image](https://user-images.githubusercontent.com/60282451/119409666-4a104b00-bd05-11eb-90f2-19470bc3d204.png)

**Comment by L1ghtn1ng** [comment]
I cannot replicate this with master, what version of kali and dnsrecon you using?

**Comment by filippolauria** [comment]
@Sharmitanmay this bug is related to an older version of dnsrecon. Update to latest version to solve the issue.

**Comment by L1ghtn1ng** [comment]
I cannot replicate this with master, what version of kali and dnsrecon you using?
