### ISSUE TITLE
[Feature Request] Installation docs

### ISSUE THREAD

**Issue by Swazimodo** [darkoperator/dnsrecon#193]
**Feature Request or Bug or Other**
Feature Request

**Describe the feature request or bug or other**
It would be really nice if the readme had installation instructions to use in another python script

**To Reproduce**
I tried to pip install this a few ways and it always failed:
`pip install https://github.com/darkoperator/dnsrecon.git`
`pip install https://github.com/darkoperator/dnsrecon/archive/refs/tags/0.10.1.tar.gz`
`pip install https://github.com/darkoperator/dnsrecon/releases/tag/0.10.1`

**Expected behaviour**
Installation documentation exists and following the steps will be successful

**System Information (System that tool is running on):**
 - OS: macOS 11.4
 - Python version: 3.8

**Additional context**
Hoping to run this as a python module but could call this as a cli using `subprocess.check_output`

**Comment by L1ghtn1ng** [comment]
@Swazimodo you can install it by cloning the repo and running setup.py install or you can use the dockerfile to create a container, hope that helps, sorry for taking ages to get back to you.
