### ISSUE TITLE
Bug: Receiving Error on WSL Kali

### ISSUE THREAD

**Issue by bp32795** [darkoperator/dnsrecon#195]
I am attempting to run DNSRecon on Kali on Windows Subsystem for Linux and I am getting the following error. 

```
Traceback (most recent call last):
  File "/usr/share/dnsrecon/./dnsrecon.py", line 1705, in <module>
    main()
  File "/usr/share/dnsrecon/./dnsrecon.py", line 1664, in main
    std_enum_records = general_enum(res, domain, xfr, bing, yandex, spf_enum, do_whois, do_crt, zonewalk)
  File "/usr/share/dnsrecon/./dnsrecon.py", line 1069, in general_enum
    zone_info = ds_zone_walk(res, domain, request_timeout)
NameError: name 'request_timeout' is not defined
```
I am running `dnsrecon -d weberdns.de -z` and that succeeds until whatever happens after Enumerating SRV Records. After that, it errors out with the above. 

I am guessing this may be related to WSL, but unsure. I have tried to specify --lifetime, but that does not make a difference. 

**System Information (System that tool is running on):**
 - OS: WSL 1, Windows 10,[ Kali package from here. ](https://www.microsoft.com/store/apps/9PKR34TNCV07)

Full output:
```
[*] Performing General Enumeration of Domain: weberdns.de
[*] DNSSEC is configured for weberdns.de
[*] DNSKEYs:
[*]     None KSk RSASHA256 03010001b0698ae5f8db77bc1c009402 f011333507facb6a30016ad239ad85f0 3b15073c779b2a31f65c2b4bdc838405 228b4054887c01f0138201cfeed232ea b56e2aa0a7bc5e0b15a9f838d359edcd d684b3221c1f3417833ce4d99130c87f b2c6f7d97d744e1fa2377836bcf26dbc ffabc68791553e57c8dc1b0c1f805026 60b04970c119a007e50f40f2d4d69660 f5b38a5b4ede8ddb5aca9948b4faa2b8 b439791a7c39679bf7602d4a900e469f 20e2985cf9cb6fa07f5aefd94b0accd3 5e288981a5b7f222f00f9ad91efaa628 bea64aafea120c5a4079298629f27d82 7b6331fe91b98e9fb5970a07db8d2ad5 6218825de2be34a1a06d4c099706c755 f7582d53
[*]     None ZSK RSASHA256 03010001bd677a3655d63dd057549cf9 edbab1234eda639d24769749e7fe2979 aab838b31bc2be643e8b28e4cccd0638 f34db9b65826ec708841c997867c1ef1 c5582ad3b47a3cf1b6b1f4d62be666b5 09240362da6c1f3a5a462a3460e2c4ad 4dbbf4afb87b93843836beb52c4faf72 fc9967f0fbe46450002c8bac764fcf47 20a082fd
[*]      SOA ns0.weberdns.de 194.247.5.13
[*]      NS ns2.weberdns.de 194.247.5.14
[*]      NS ns2.weberdns.de 2001:470:1f0b:16b0::a26:53
[*]      NS ns1.weberdns.de 37.24.166.86
[*]      NS ns1.weberdns.de 2001:470:7250::a25:53
[*]      MX mail.weberdns.de 87.190.30.115
[*]      MX mail.weberdns.de 2003:de:2016:110::d01:25
[*]      A weberdns.de 194.247.5.26
[*]      AAAA weberdns.de 2001:470:1f0b:16b0:6986:b8d4:3649:9cbe
[*] Enumerating SRV Records
[+]      SRV _sip._tcp.weberdns.de test.weberdns.de 198.51.100.42 5060
[+]      SRV _sip._tcp.weberdns.de test.weberdns.de 2001:db8::198:51:100:42 5060
[+]      SRV _sip._udp.weberdns.de test.weberdns.de 198.51.100.42 5060
[+]      SRV _sip._udp.weberdns.de test.weberdns.de 2001:db8::198:51:100:42 5060
[+]      SRV _sip._tls.weberdns.de test.weberdns.de 198.51.100.42 433
[+]      SRV _sip._tls.weberdns.de test.weberdns.de 2001:db8::198:51:100:42 433
[+] 6 Records Found
Traceback (most recent call last):
  File "/usr/share/dnsrecon/./dnsrecon.py", line 1705, in <module>
    main()
  File "/usr/share/dnsrecon/./dnsrecon.py", line 1664, in main
    std_enum_records = general_enum(res, domain, xfr, bing, yandex, spf_enum, do_whois, do_crt, zonewalk)
  File "/usr/share/dnsrecon/./dnsrecon.py", line 1069, in general_enum
    zone_info = ds_zone_walk(res, domain, request_timeout)
NameError: name 'request_timeout' is not defined
```

**Comment by L1ghtn1ng** [comment]
Can you please make sure you have a fully up to date Kali release please and after doing that retry  again and see if you get the issue?
________________________________
From: bp32795 ***@***.***>
Sent: Wednesday, July 21, 2021 3:45:58 PM
To: darkoperator/dnsrecon ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [darkoperator/dnsrecon] Bug: Receiving Error on WSL Kali (#195)


I am attempting to run DNSRecon on Kali on Windows Subsystem for Linux and I am getting the following error.

Traceback (most recent call last):
  File "/usr/share/dnsrecon/./dnsrecon.py", line 1705, in <module>
    main()
  File "/usr/share/dnsrecon/./dnsrecon.py", line 1664, in main
    std_enum_records = general_enum(res, domain, xfr, bing, yandex, spf_enum, do_whois, do_crt, zonewalk)
  File "/usr/share/dnsrecon/./dnsrecon.py", line 1069, in general_enum
    zone_info = ds_zone_walk(res, domain, request_timeout)
NameError: name 'request_timeout' is not defined


I am running dnsrecon -d weberdns.de -z and that succeeds until whatever happens after Enumerating SRV Records. After that, it errors out with the above.

I am guessing this may be related to WSL, but unsure. I have tried to specify --lifetime, but that does not make a difference.

System Information (System that tool is running on):

  *   OS: WSL 1, Windows 10, Kali package from here. <https://www.microsoft.com/store/apps/9PKR34TNCV07>

Full output:

[*] Performing General Enumeration of Domain: weberdns.de
[*] DNSSEC is configured for weberdns.de
[*] DNSKEYs:
[*]     None KSk RSASHA256 03010001b0698ae5f8db77bc1c009402 f011333507facb6a30016ad239ad85f0 3b15073c779b2a31f65c2b4bdc838405 228b4054887c01f0138201cfeed232ea b56e2aa0a7bc5e0b15a9f838d359edcd d684b3221c1f3417833ce4d99130c87f b2c6f7d97d744e1fa2377836bcf26dbc ffabc68791553e57c8dc1b0c1f805026 60b04970c119a007e50f40f2d4d69660 f5b38a5b4ede8ddb5aca9948b4faa2b8 b439791a7c39679bf7602d4a900e469f 20e2985cf9cb6fa07f5aefd94b0accd3 5e288981a5b7f222f00f9ad91efaa628 bea64aafea120c5a4079298629f27d82 7b6331fe91b98e9fb5970a07db8d2ad5 6218825de2be34a1a06d4c099706c755 f7582d53
[*]     None ZSK RSASHA256 03010001bd677a3655d63dd057549cf9 edbab1234eda639d24769749e7fe2979 aab838b31bc2be643e8b28e4cccd0638 f34db9b65826ec708841c997867c1ef1 c5582ad3b47a3cf1b6b1f4d62be666b5 09240362da6c1f3a5a462a3460e2c4ad 4dbbf4afb87b93843836beb52c4faf72 fc9967f0fbe46450002c8bac764fcf47 20a082fd
[*]      SOA ns0.weberdns.de 194.247.5.13
[*]      NS ns2.weberdns.de 194.247.5.14
[*]      NS ns2.weberdns.de 2001:470:1f0b:16b0::a26:53
[*]      NS ns1.weberdns.de 37.24.166.86
[*]      NS ns1.weberdns.de 2001:470:7250::a25:53
[*]      MX mail.weberdns.de 87.190.30.115
[*]      MX mail.weberdns.de 2003:de:2016:110::d01:25
[*]      A weberdns.de 194.247.5.26
[*]      AAAA weberdns.de 2001:470:1f0b:16b0:6986:b8d4:3649:9cbe
[*] Enumerating SRV Records
[+]      SRV _sip._tcp.weberdns.de test.weberdns.de 198.51.100.42 5060
[+]      SRV _sip._tcp.weberdns.de test.weberdns.de 2001:db8::198:51:100:42 5060
[+]      SRV _sip._udp.weberdns.de test.weberdns.de 198.51.100.42 5060
[+]      SRV _sip._udp.weberdns.de test.weberdns.de 2001:db8::198:51:100:42 5060
[+]      SRV _sip._tls.weberdns.de test.weberdns.de 198.51.100.42 433
[+]      SRV _sip._tls.weberdns.de test.weberdns.de 2001:db8::198:51:100:42 433
[+] 6 Records Found
Traceback (most recent call last):
  File "/usr/share/dnsrecon/./dnsrecon.py", line 1705, in <module>
    main()
  File "/usr/share/dnsrecon/./dnsrecon.py", line 1664, in main
    std_enum_records = general_enum(res, domain, xfr, bing, yandex, spf_enum, do_whois, do_crt, zonewalk)
  File "/usr/share/dnsrecon/./dnsrecon.py", line 1069, in general_enum
    zone_info = ds_zone_walk(res, domain, request_timeout)
NameError: name 'request_timeout' is not defined

**Comment by bp32795** [comment]
Ran full-upgrade, same issue. Any other information you need?

**Comment by L1ghtn1ng** [comment]
Can you try using git version and a python virtual environment and see if you get the issue?
________________________________

**Comment by photoemulator** [comment]
I was getting the same error.
But then I issued this command:
   ./dnsrecon.py -d cisco.com
And it worked!!!!  Freaking commands!!!!

**Comment by stePh-here** [comment]
> I am attempting to run DNSRecon on Kali on Windows Subsystem for Linux and I am getting the following error.
> 
> ```
> Traceback (most recent call last):
>   File "/usr/share/dnsrecon/./dnsrecon.py", line 1705, in <module>
>     main()
>   File "/usr/share/dnsrecon/./dnsrecon.py", line 1664, in main
>     std_enum_records = general_enum(res, domain, xfr, bing, yandex, spf_enum, do_whois, do_crt, zonewalk)
>   File "/usr/share/dnsrecon/./dnsrecon.py", line 1069, in general_enum
>     zone_info = ds_zone_walk(res, domain, request_timeout)
> NameError: name 'request_timeout' is not defined
> ```
> 
> I am running `dnsrecon -d weberdns.de -z` and that succeeds until whatever happens after Enumerating SRV Records. After that, it errors out with the above.
> 
> I am guessing this may be related to WSL, but unsure. I have tried to specify --lifetime, but that does not make a difference.
> 
> **System Information (System that tool is running on):**
> 
> * OS: WSL 1, Windows 10,[ Kali package from here. ](https://www.microsoft.com/store/apps/9PKR34TNCV07)
> 
> Full output:
> 
> ```
> [*] Performing General Enumeration of Domain: weberdns.de
> [*] DNSSEC is configured for weberdns.de
> [*] DNSKEYs:
> [*]     None KSk RSASHA256 03010001b0698ae5f8db77bc1c009402 f011333507facb6a30016ad239ad85f0 3b15073c779b2a31f65c2b4bdc838405 228b4054887c01f0138201cfeed232ea b56e2aa0a7bc5e0b15a9f838d359edcd d684b3221c1f3417833ce4d99130c87f b2c6f7d97d744e1fa2377836bcf26dbc ffabc68791553e57c8dc1b0c1f805026 60b04970c119a007e50f40f2d4d69660 f5b38a5b4ede8ddb5aca9948b4faa2b8 b439791a7c39679bf7602d4a900e469f 20e2985cf9cb6fa07f5aefd94b0accd3 5e288981a5b7f222f00f9ad91efaa628 bea64aafea120c5a4079298629f27d82 7b6331fe91b98e9fb5970a07db8d2ad5 6218825de2be34a1a06d4c099706c755 f7582d53
> [*]     None ZSK RSASHA256 03010001bd677a3655d63dd057549cf9 edbab1234eda639d24769749e7fe2979 aab838b31bc2be643e8b28e4cccd0638 f34db9b65826ec708841c997867c1ef1 c5582ad3b47a3cf1b6b1f4d62be666b5 09240362da6c1f3a5a462a3460e2c4ad 4dbbf4afb87b93843836beb52c4faf72 fc9967f0fbe46450002c8bac764fcf47 20a082fd
> [*]      SOA ns0.weberdns.de 194.247.5.13
> [*]      NS ns2.weberdns.de 194.247.5.14
> [*]      NS ns2.weberdns.de 2001:470:1f0b:16b0::a26:53
> [*]      NS ns1.weberdns.de 37.24.166.86
> [*]      NS ns1.weberdns.de 2001:470:7250::a25:53
> [*]      MX mail.weberdns.de 87.190.30.115
> [*]      MX mail.weberdns.de 2003:de:2016:110::d01:25
> [*]      A weberdns.de 194.247.5.26
> [*]      AAAA weberdns.de 2001:470:1f0b:16b0:6986:b8d4:3649:9cbe
> [*] Enumerating SRV Records
> [+]      SRV _sip._tcp.weberdns.de test.weberdns.de 198.51.100.42 5060
> [+]      SRV _sip._tcp.weberdns.de test.weberdns.de 2001:db8::198:51:100:42 5060
> [+]      SRV _sip._udp.weberdns.de test.weberdns.de 198.51.100.42 5060
> [+]      SRV _sip._udp.weberdns.de test.weberdns.de 2001:db8::198:51:100:42 5060
> [+]      SRV _sip._tls.weberdns.de test.weberdns.de 198.51.100.42 433
> [+]      SRV _sip._tls.weberdns.de test.weberdns.de 2001:db8::198:51:100:42 433
> [+] 6 Records Found
> Traceback (most recent call last):
>   File "/usr/share/dnsrecon/./dnsrecon.py", line 1705, in <module>
>     main()
>   File "/usr/share/dnsrecon/./dnsrecon.py", line 1664, in main
>     std_enum_records = general_enum(res, domain, xfr, bing, yandex, spf_enum, do_whois, do_crt, zonewalk)
>   File "/usr/share/dnsrecon/./dnsrecon.py", line 1069, in general_enum
>     zone_info = ds_zone_walk(res, domain, request_timeout)
> NameError: name 'request_timeout' is not defined
> ```

after the full upgrade on wsl kali receiving the same error. Any updates on this??

**Comment by L1ghtn1ng** [comment]
Closing due to timeout. Please try the git version and if you get this issue please re-open

**Comment by TheParmak** [comment]
it errors for me if I specify the -z option no problem without that
