### ISSUE TITLE
Crash after install python3

### ISSUE THREAD

**Issue by gprime31** [darkoperator/dnsrecon#211]
after python3 setup.py install
![2022-02-17_20-42](https://user-images.githubusercontent.com/44535257/154601596-51c816f4-13d8-4a81-8b29-4e22c63821d6.png)

**Comment by gprime31** [comment]
Fixed using:
python3 -m pip install dnsrecon
DNSRecon version 0.10.1 ( http://www.darkoperator.com )

**Comment by L1ghtn1ng** [comment]
Can you do a git pull please as this should be fixed now

**Comment by gprime31** [comment]
> Can you do a git pull please as this should be fixed now

Works now.
Thanks
