### ISSUE TITLE
Reverse Lookup Range is Exclusive

### ISSUE THREAD

**Issue by harmonherring** [darkoperator/dnsrecon#219]
Not sure if this is intended functionality or not. When performing a reverse lookup on an IP address range, no reverse lookup is performed on the last IP address in the range.

For example, when performing a reverse lookup on the range 192.168.1.0/24, no reverse lookup is performed on 192.168.1.255. 

Is this functionality intended? If not, I'd like to open a pull request to try and get this fixed. Thanks.

**Comment by L1ghtn1ng** [comment]
Yeah it will be intended as the .255 address is the broadcast address and that will be why

On 7 Apr 2022, at 03:33, Harmon Herring ***@***.***> wrote:

﻿

Not sure if this is intended functionality or not. When performing a reverse lookup on an IP address range, no reverse lookup is performed on the last IP address in the range.

For example, when performing a reverse lookup on the range 192.168.1.0/24, no reverse lookup is performed on 192.168.1.255.

Is this functionality intended? If not, I'd like to open a pull request to try and get this fixed. Thanks.

**Comment by hlein** [comment]
> Yeah it will be intended as the .255 address is the broadcast address and that will be why

This might not be true. Perhaps the target network is larger like a /20, but you know all the targets you're interested in are within one /24. Or there's a /24 network but you can see from delegations that only /27 worth of them belong to your targets. More generally, you might be given a list of ranges/netblocks that are in scope, but that doesn't say anything about the network addressing that those targets live in. What harm would one extra DNS query per range do?
