### ISSUE TITLE
[Feature Request] Support multiple ranges with -r / --range

### ISSUE THREAD

**Issue by hlein** [darkoperator/dnsrecon#220]
**Feature Request or Bug or Other**
Feature Request

**Describe the feature request or bug or other**
It would be nice if `--range` could take more than one range/cidr. Since `--name_server` already takes multiple comma-separated values, that syntax for `--range` would make sense.

The provided range is expanded into `rvl_ip_list`, which is then passed to `brute_reverse` as `ip_list`. It looks like the status message in `brute_reverse` has an assumption that its targets in `ip_list` are contiguous but the code breaking off `ip_group` sized chunks and doing the work doesn't actually seem to care.

**Comment by darkoperator** [comment]
I would not expand full ranges in memory, gets messy quickly in terms of memory use. Bit me when I wrote dnsrecon 0.1 in ruby a long time ago and even when ported to python using a proper ip address library better to handle each range individually and let the ip Address library iterate providing the next value and just work in chunks to keep memory use manageable
