### ISSUE TITLE
[Bug] Bruteforce subdomains using a dictionary

### ISSUE THREAD

**Issue by h49nakxs** [darkoperator/dnsrecon#227]
**Feature Request or Bug or Other**
Bug

**Describe the feature request or bug or other**
Bruteforce subdomains using a dictionary doesn't work.

**To Reproduce**
Steps to reproduce the behaviour:
1. dnsrecon -D subdomains-top1million-20000.txt -d xxx -n 192.168.xx.xx -t brt
2. [-] No valid dictionary files have been specified or found within the tool

**Expected behaviour**
dnsrecon trying to resolve subdomains using the list provided.

**System Information (System that tool is running on):**
DNSRecon version 1.1.0
Linux host 5.16.0-kali7-amd64
Python 3.10.4

**Additional context**
I've tried several different lists, including a list just containing one "test" line, no one worked. I've tried many variations of the command but it didn't solve the issue.

**Comment by L1ghtn1ng** [comment]
@h49nakxs I cannot replicate your issue, the only thing that I can see is the fact that if its in your current directory then you are missing ./ at the beginning of the path to the namelist 
![image](https://user-images.githubusercontent.com/3628354/173256135-643e2f50-6bda-476a-b47c-ffc6feaa2293.png)

Here is me doing it your way with the ./prefix as it is in my current directory
![image](https://user-images.githubusercontent.com/3628354/173256192-f29aff24-0c27-4f4c-a8e1-69b6155eba20.png)

**Comment by h49nakxs** [comment]
Hi,

Yes, sorry I've missed the the ./ but only in my message, not in my tests :

![dnsrecon](https://user-images.githubusercontent.com/100863696/173384795-526855ce-740b-44a5-a2c6-db2cbcfcbf93.jpg)

It seems to work now when entering the full path (which is strange because I thought I've already tested it without success but anyway).

**Comment by h49nakxs** [comment]
Hi,

After digging a little bit more, it appears that this bug is more related to Kali than dnsrecon.
I have opened a bug report in the Kali bug tracker : https://bugs.kali.org/view.php?id=7761

Thanks anyway for your consideration.

**Comment by L1ghtn1ng** [comment]
It’s actually a Debian bug as they are the ones that package it and kali just pulls it from them. It is good that you have created that ticket and I will reach out to the package maintenance for Debian and see what he comes back with

On 17 Jun 2022, at 12:03, h49nakxs ***@***.***> wrote:

﻿

Hi,

After digging a little bit more, it appears that this bug is more related to Kali than dnsrecon.
I have opened a bug report in the Kali bug tracker : https://bugs.kali.org/view.php?id=7761

Thanks anyway for your consideration.

**Comment by L1ghtn1ng** [comment]
Sorry for the delay in this I have updated the kali ticket and have emailed the Debian package maintainers so hopefully they will get to it soon

**Comment by L1ghtn1ng** [comment]
this should be fixed now
