### ISSUE TITLE
AttributeError: module 'urllib' has no attribute 'urlopen'. I tried urllib.request.urlopen, but another AttributeError showed. Any fixes?

### ISSUE THREAD

**Issue by AK19ua** [darkoperator/dnsrecon#232]
import urllib
import urllib.parse, urllib.error
import urllib.request
from urllib.request import urlopen
from bs4 import BeautifulSoup
import ssl

ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

url = input('Enter - ')
html = urllib.urlopen(url).read()
soup = BeautifulSoup(html,"html.parser")

# Retrive 
tags = soup('span')

spans = [int(tag.contents[0]) for tag in tags]
total = sum(spans)
print(total)
![Снимок экрана 2023-01-01 194936](https://user-images.githubusercontent.com/120457988/210180197-4a77fc87-fced-4407-a620-22c4dee0e287.png)

**Comment by L1ghtn1ng** [comment]
This is for posting about issues with DNSrecon but your issue is you need to do urllib.request.urlopen(url).read()
