### ISSUE TITLE
output not saved when invalid type given

### ISSUE THREAD

**Issue by digininja** [darkoperator/dnsrecon#24]
I just made a typo when entering the types

-t brt,axfr

but I'd also specified -c to save to file. The brute force ran but then nothing was saved as it tried to do the axft and failed. It should save at the end of each phase rather than at the end and it should also check the types before doing anything else to detect typos.

**Comment by darkoperator** [comment]
Will add it to the list for after vacation :)

**Comment by darkoperator** [comment]
fixed in latest version

**Comment by digininja** [comment]
Thanks
