### ISSUE TITLE
dnsrecon problem

### ISSUE THREAD

**Issue by deliali666** [darkoperator/dnsrecon#243]
**_### I can take result on nslookup but i can not take result from dnsrecon? What can be the problem?_**

┌──(root㉿HUSTAD)-[~]
└─# nslookup teknosa.com   
Server:         192.168.58.2
Address:        192.168.58.2#53

Non-authoritative answer:
Name:   teknosa.com
Address: 85.111.64.28

                                                                             
┌──(root㉿HUSTAD)-[~]
└─# dnsrecon -d teknosa.com
[*] std: Performing General Enumeration against: teknosa.com...
[-] A timeout error occurred please make sure you can reach the target DNS Servers
[-] directly and requests are not being filtered. Increase the timeout from 3.0 second
[-] to a higher number with --lifetime <time> option.
                                                                             
┌──(root㉿HUSTAD)-[~]
└─#

**Comment by L1ghtn1ng** [comment]
did you try with a higher timeout?

**Comment by L1ghtn1ng** [comment]
timeout
