### ISSUE TITLE
Incorrect regex causes failure - Record NSEC3  - write_db

### ISSUE THREAD

**Issue by FrankSpierings** [darkoperator/dnsrecon#27]
Line 782 of dnsrecon.py will process NSEC3 records, which results in a stacktrace as shown below:

Traceback (most recent call last):
  File "dnsrecon.py", line 1666, in <module>
    main()
  File "dnsrecon.py", line 1638, in main
    write_db(results_db, returned_records)
  File "dnsrecon.py", line 784, in write_db
    'values( "%(type)s", "%(target)s", "%(address)s" )' % n
KeyError: 'target'

Suggestion for a fix (line 782):
        elif re.match(r'NS$', n['type']):

**Comment by darkoperator** [comment]
will get to ll the issues you opened tonight :) Thanks for reporting the issues.

**Comment by FrankSpierings** [comment]
That would be great! I would love to be able to consistently use the tool during pentests. Saves me all the manual 'dig' labour ;)

**Comment by FrankSpierings** [comment]
This is fixed when using sqlite as output. I'm also testing csv and xml output. This should be the fix for a similar problem in csv output.

@@ -715,7 +715,7 @@ def make_csv(data):
             if re.search(r'PTR|^[A]$|AAAA', n['type']):
                 csv_data += n['type'] + "," + n['name'] + "," + n['address'] + "\n"
 
-            elif re.search(r'NS', n['type']):
+            elif re.search(r'NS$', n['type']):
                 csv_data += n['type'] + "," + n['target'] + "," + n['address'] + "\n"
 
             elif re.search(r'SOA', n['type']):

**Comment by FrankSpierings** [comment]
The issue for xml is different. I'll open another ticket.

**Comment by darkoperator** [comment]
Fix applied and tested.

**Comment by FrankSpierings** [comment]
Confirmed, closing ticket.
