### ISSUE TITLE
Incorrect type causes failure - PTR - write_db

### ISSUE THREAD

**Issue by FrankSpierings** [darkoperator/dnsrecon#29]
While writing PTR records to the sqlite database, the following failure will occur.

At line 776, variable 'n' is used to iterate through the array 'data'. In the following lines, 'n' is assumed to be of the type 'list'.
When using reverse lookups to resolve PTR records, this breaks as shown below:

  File "dnsrecon.py", line 1666, in <module>
    main()
  File "dnsrecon.py", line 1638, in main
    write_db(results_db, returned_records)
  File "dnsrecon.py", line 778, in write_db
    if re.match(r'PTR|^[A]$|AAAA', n['type']):
TypeError: list indices must be integers, not str

This error occurs, because the PTR records aren't stored as separate items in the list 'data'. Instead all the PTR records together are an array (or a list by itself ... not sure... ).

I don't have a suggested fix, but it should be somewhere in the output of the reverse lookups.

**Comment by FrankSpierings** [comment]
This seems to fix it:

line 1060:
            for r in whois_rcd:
                returned_records.extend(r)

**Comment by darkoperator** [comment]
fixes applied can you test to confirm and close the issues?

**Comment by FrankSpierings** [comment]
This specific issue seems fixed. Thanks!
