### ISSUE TITLE
Bug: "List index out of range" error when using verbose tag on brute reverse against IP range/CIDR

### ISSUE THREAD

**Issue by skyhacker1** [darkoperator/dnsrecon#290]
**Feature Request or Bug or Other**
Bug

**Describe the feature request or bug or other**
When using the -v verbose parameter with brute reverse, a "List index out of range" error occurs. Without the -v parameter the code executes without error. The problem is with line 441 in cli.py when attempting to set the ipaddress variable:
`ipaddress = str(ip_list[x])`

**To Reproduce**
`python3 ./dnsrecon.py -v -r [CIDR/IP range]`

**Expected behaviour**
The -v verbose tag should result in displaying each IP address attempted in reverse DNS PTR query.

**Screenshots**
When adding the -v (verbose) tag results in "List index out of range" error
![image](https://github.com/darkoperator/dnsrecon/assets/173199569/9af54dac-5156-45a4-a265-94d56efd43e6)

**System Information (System that tool is running on):**
 - OS: Kali Linux WSL on Windows 11
 - Version 1.2.0 (latest)

**Additional context**
Code issue in brute_reverse function in cli.py:
![image](https://github.com/darkoperator/dnsrecon/assets/173199569/8290547f-c68a-48a3-a38e-3feebe50fe96)

Proposed fix (or what I did to get it to work, without any regression testing):
![image](https://github.com/darkoperator/dnsrecon/assets/173199569/3ee460cb-2110-4689-bf0b-89520462fd0e)

**Comment by L1ghtn1ng** [comment]
Submit your fix in a MR and I can take a look ☺️
