### ISSUE TITLE
Writing to XML fails when the record data is not unicode (compatible)

### ISSUE THREAD

**Issue by FrankSpierings** [darkoperator/dnsrecon#30]
Records are translated to key value pairs before passing them to the prettify function, when writing data to XML.
The prettify function tries to encode these pairs into unicode. This could fail if the string contains bytes > 128 dec.

The problem starts around line 657, but will only be noticed at around line 643 (ElementTree.tostring)

My lousy fix is the following, but I'm sure real programmers would come up with something more decent:

```
@@ -657,7 +657,14 @@ def dns_record_from_dict(record_dict_list, scan_info, domain):
         if type(r) is not str:
             try:
                 for k, v in r.items():
-                    elem.attrib[k] = v
+                    try:
+                        k = unicode(str(k))
+                        v = unicode(str(v))
+                        elem.attrib[k] = v
+                    except:
+                        print ("Could not convert key or value to unicode: '%s = %s'" % (repr(k), repr(v)))
+                        print ("In element: %s" % repr(elem.attrib))
+                        continue
                 xml_doc.append(elem)
             except AttributeError:
                 continue
```

**Comment by darkoperator** [comment]
What would be a real world example where that would happen?

**Comment by FrankSpierings** [comment]
Please see your email. I send you an example command with a domain in which it occurs. It seems to happen in a NSEC3 record, when getting the salt. I don't know why. It might be a problem in dnspython.

**Comment by darkoperator** [comment]
a pull request would have been nicer ;) been a couple of years since I have used patch

**Comment by FrankSpierings** [comment]
I understand. I'm a github n00b, so that why I did it this way. I will try to improve :)

**Comment by darkoperator** [comment]
ok made the changes and also think I made it so it would never happen by turning the salt value in to HEX in the parsing of the AXFR

**Comment by FrankSpierings** [comment]
Your part of the fix seems way better than my part ;)

**Comment by darkoperator** [comment]
Happy for all the help, DNS can be configured in so many ways and each server with its own take, plus my bad coding :) every bit counts

**Comment by FrankSpierings** [comment]
No problem! Its much better for me to fix things than to start from scratch, it saves a lot of time. I might have another thing I need fixed. Working on it now. Will report back when I know more.
