### ISSUE TITLE
[Bug] dnsrecon creates '~' in working directory

### ISSUE THREAD

**Issue by yigitsever** [darkoperator/dnsrecon#324]
Bug

dnsrecon creates a directory "~" under the current working directory. 

A log file is created under `.config` inside '~' directory.

**Additional context**

This behaviour is caused by the following line: https://github.com/darkoperator/dnsrecon/blob/master/dnsrecon/cli.py#L1665

The "~/.config" is not expanded to user's home directory but under the current directory. 

Something like:

```python
logger.add(Path(Path.home(), '.config/dnsrecon/dnsrecon.log'), rotation='100 MB', compression='tar.gz')
```

Fixes this issue.

**Comment by L1ghtn1ng** [comment]
If you want to put a MR in I can merge it or when I get a sec today can implement your fix ☺️
