### ISSUE TITLE
Missing final character to CNAME entry when type is AXFR

### ISSUE THREAD

**Issue by kartoch** [darkoperator/dnsrecon#35]
$ dig AXFR blabla.fr @dns.blabla.fr | grep webuse
    lamort.blabla.fr.	21600	IN	CNAME	webuser.blabla.fr.
    webuser.blabla.fr.	21600	IN	A	1.2.3.4

Doing same operation with `dnsrecon` and JSON output:

    [
        {
        "arguments": "dnsrecon/dnsrecon.py -t axfr -d blabla.fr -n dns.blabla.fr --json samples/dnsrecon-axfr-blabla.fr.json",
        "date": "2015-03-03 11:52:43.031781",
        "type": "ScanInfo"
        },

    ...
      {
        "address": "1.2.3.4",
        "name": "webuser.blabla.fr",
        "type": "A",
        "zone_server": "X.X.X.X"
      },
    ...
      {
        "address": "1.2.3.4",
        "name": "lamort.blabla.fr",
        "target": "webuse",
        "type": "CNAME",
        "zone_server": "X.X.X.X"
      },
    ...
    ]  

'webuser' becomes 'webuse' with 'dnsrecon'.

**Comment by darkoperator** [comment]
I think I resolve the issue in my last commit can you confirm

**Comment by kartoch** [comment]
Yes bb5ce03228750142cb56a8165a429937fe8aff35 fixs it
