### ISSUE TITLE
Error on basic scan

### ISSUE THREAD

**Issue by digininja** [darkoperator/dnsrecon#37]
Colleague got this doing a basic scan with output to CSV, didn't send me full command line. I ran similar scan with brute force and zone transfer and it worked OK. I think he re-ran the command without .csv on filename and it worked but this could have been coincidence or he could have changed something else.

```
Traceback (most recent call last):
  File "./dnsrecon.py", line 1676, in <module>
      main()
        File "./dnsrecon.py", line 1653, in main
            write_to_file(make_csv(returned_records), csv_file)
              File "./dnsrecon.py", line 753, in make_csv
                  csv_data += n['type'] + "," + n['name'] + ",," + n['target'] + ",\n"
                  KeyError: 'target'
```

**Comment by darkoperator** [comment]
is he running the latest version from GitHub and not the one that comes with Kali?

**Comment by digininja** [comment]
Told him to get it from GitHub, can confirm if you think he didn't.

**Comment by darkoperator** [comment]
have him do it, I can not reproduce and I do know that a month or two a similar issue was fixed.
