### ISSUE TITLE
Create Distribution Package and Upload to PyPi

### ISSUE THREAD

**Issue by makefu** [darkoperator/dnsrecon#41]
I'd love to be able to install dnsrecon via pypi instead of cloning the repo and installing dependencies manually.
The project would need a setup.py file, uploading to pypi is straight-forward.

**Comment by Miserlou** [comment]
Plus one!

**Comment by L1ghtn1ng** [comment]
Got a setup.py now in master

**Comment by makefu** [comment]
Thanks!
