### ISSUE TITLE
Support Multiple Resolvers

### ISSUE THREAD

**Issue by indolering** [darkoperator/dnsrecon#43]
Most resolvers don't pass along IP address information, so you should be able to scale up brute force attacks by spreading queries across multiple resolvers.

You could include a list of popular servers by default (Verizon, Google, OpenDNS, etc).  [Public-DNS.tk](http://public-dns.tk/) maintains a list of open DNS resolvers that includes IP addresses and uptime statistics.  You could download it on demand and filter them based on uptime, there are ~50K IP addresses with a 100% uptime rating.  I would recommend you shuffle and throttle to 5 queries per second.

**Comment by tsellers-r7** [comment]
@indolering - FYI, basic support for multiple resolvers was added in 0.9.0.  It doesn't load balance among them but does use `random.shuffle` to reorder them during most calls.
