### ISSUE TITLE
DNS Recon fails to check AXFR transfers properly 

### ISSUE THREAD

**Issue by Alex-UK-PL** [darkoperator/dnsrecon#48]
The problem relates to specific syntax of DIG command that have to be used, standard commands or windows nslookup will also fail. 

Could you add the following check to your tool please;
'dig axfr domain.com @ns1.domain.com'

Many thanks,

Alexander

**Comment by darkoperator** [comment]
Could yoi be more specific? Against what domain os it failing against ?

**Comment by Alex-UK-PL** [comment]
Unfortunately I can not disclose this information however tool was used on updated Kali. I have attempted other tools and they all failed, including standard windows nslookup shell and manual requests. It seems 'dig axfr domain.com @ns1.domain.com' is the only syntax it works.

**Comment by darkoperator** [comment]
If I can replicate it I can’t fix it, did you tried using the dnsrecon -n s1.domain.com -t axfr -d domain.com <http://domain.com/>

**Comment by Alex-UK-PL** [comment]
It works with the syntax provided. Many thanks. I guess I had some wrong assumptions when  executing the command however when i type -t axfr I would simply assume that script will perform any variations that would result in full zone transfer.
