### ISSUE TITLE
Dns server port

### ISSUE THREAD

**Issue by alessiodallapiazza** [darkoperator/dnsrecon#56]
Good morning,
I think it would be useful to have a flag to specify the port of the dns server.

Thanks,
Alessio

**Comment by darkoperator** [comment]
Do organizations in the real world use alternate DNS port? In my experience I have not encountered it one single time in production

**Comment by clshack** [comment]
I found it in a test dns server. 
Could be great have this option.

**Comment by L1ghtn1ng** [comment]
Closing due to duplicate
