### ISSUE TITLE
links not working

### ISSUE THREAD

**Issue by angryyoung15** [darkoperator/dnsrecon#57]
I have performed `dnsrecon` on evernote.com but resulted in finding 0 SRV documents. So i tried to reverse lookup.Then it gave 504 records.
but none of those links are working. 
what to could be the possible reason for those links not working.

**Comment by darkoperator** [comment]
Links? The tool is for finding dns host records not web servers, many orgs do not have SRV records as well as PTR records for reverse lookup

**Comment by angryyoung15** [comment]
So these domains that I get after reverse look-up are affiliated to evernote but they didn't assign any web server for this. right?

**Comment by darkoperator** [comment]
Correct, DNS is not only for webservers

**Comment by angryyoung15** [comment]
How can I get all the sub-domains of an url just like the ones in here(https://github.com/JamieFarrelly/Popular-Site-Subdomains) how can I find such valuable information with DNSRECON.

**Comment by darkoperator** [comment]
Bruteforce option with a dictionary file
