### ISSUE TITLE
-d option errors if IP address is passed

### ISSUE THREAD

**Issue by joekir** [darkoperator/dnsrecon#62]
I hadn't used the tool before and was trying a few options. I incorrectly used an IP address with the domain flag option. It errored far into the code away from the input parsing, due to *line 1415 of dnsrecon.py* not validating the input format.
```
 elif opt in ('-d', '--domain'):
            domain = arg
``` 

I think it would be good to refactor this section to use [argparse](https://docs.python.org/3/library/argparse.html).

**Comment by darkoperator** [comment]
Thanks for the tip, will need to thing what is the best ways
