### ISSUE TITLE
AttributeError: module 'urllib' has no attribute 'urlopen'

### ISSUE THREAD

**Issue by fferraro87** [darkoperator/dnsrecon#66]
Hi,
i'm trying to use this tool on my arch OS.
i've this error : 
```
Traceback (most recent call last):
  File "./dnsrecon.py", line 1664, in <module>
    main()
  File "./dnsrecon.py", line 1622, in main
    spf_enum, do_whois, zonewalk)
  File "./dnsrecon.py", line 1067, in general_enum
    goo_rcd = goo_result_process(res, scrape_google(domain))
  File "./dnsrecon.py", line 531, in scrape_google
    sock = urllib.urlopen(url)
AttributeError: module 'urllib' has no attribute 'urlopen'

```

what i've to install?
thanks

**Comment by darkoperator** [comment]
Only dnspython and netaddr. What version of Python are you using?

**Comment by fferraro87** [comment]
Python 3.6.0, i've already install dnspython and netaddr via pip

**Comment by darkoperator** [comment]
Looks like I will have to refactor the code to work with 3.x
http://stackoverflow.com/questions/3969726/attributeerror-module-object-has-no-attribute-urlopen <http://stackoverflow.com/questions/3969726/attributeerror-module-object-has-no-attribute-urlopen>

**Comment by fferraro87** [comment]
Ah ok thanks for your help

**Comment by paliitr** [comment]
@darkoperator Hey. I refactored the code but that threw up a HTTP403:Forbidden. I think Google servers are rejecting requests from urllib python.

PS: I do not ping Google servers using scripts that often, so blocking my IP is not an option.

**Comment by paliitr** [comment]
@darkoperator Using requests in Python3.5.2 though solves the problem. Moreover, the function unique does not work in Python3, so a workaround by using set is to be done.

**Comment by CerebralMischief** [comment]
Any updates on this?  I'm running into this problem across various shells and have resorted to using Kali Linux and avoid updating Python there - this isn't ideal and I'd rather see the issue fixed here.  I personally don't know Python well enough to make the change or I would take care of it myself and submit a PR.  Though I see other PR's have been open for a while so I'm wondering if @darkoperator is even working on this any longer. (I hope so!) :)  Thank you in advance.

**Comment by darkoperator** [comment]
@CerebralMischief not abandone, just need to set time to figure how to keep it compatible with python 2.7 and 3.x and python breaking stuff in minor changes does not help, specially since Python is not a strength of mine

**Comment by CerebralMischief** [comment]
I'm so happy to hear you're still working on this project!  Thank you for taking the time to respond.  I am in the same boat, I don't know Python very well or I'd happily work on a fix and submit a PR.  Maybe I can try to dig in and learn it as I'd love to help you. :)

**Comment by darkoperator** [comment]
Actually thinking of removing the Google feature. It is against Google terms of service and it is not actually a DNS enumeration technique. While testing I banned my IP for a while.

**Comment by darkoperator** [comment]
Pushed a fix to master. Test and let me know if it fixed the issue.

**Comment by sokeyo** [comment]
make sure you import requests from urllib, then try this format, it worked for me:

    from urllib import request
    urllib.request.urlopen( )

**Comment by yanxg** [comment]
Change urllib.urlopen to urllib.request.urlopen in python3 might help. It solves my bug.

**Comment by tilaktok** [comment]
[!] Something went wrong, printing the error: module 'urllib' has no attribute 'urlopen'

getting error while cloning help me
