### ISSUE TITLE
brt_enum_records are not added to returned_records if domain file is not specified

### ISSUE THREAD

**Issue by ilsani** [darkoperator/dnsrecon#69]
In bruteforce mode founded records are not wrote to the output file because `brt_enum_records` are not added to `returned_records`.

Issue: https://github.com/darkoperator/dnsrecon/blob/master/dnsrecon.py#L1535

Sample command:
``` python dnsrecon.py --domain <domain> --type brt --threads 1 --iw --json out.json ```

I attached a proposed patch:
[dnsrecon.txt](https://github.com/darkoperator/dnsrecon/files/1066355/dnsrecon.txt)

GIT SHA:
`c96739859cc25177df0a9a3a3b7bdcfe62d87394` - c96739859cc25177df0a9a3a3b7bdcfe62d87394

**Comment by darkoperator** [comment]
I'm not able to replicate the issue with the current code in master.
