### ISSUE TITLE
ImportError: No module named dns.message

### ISSUE THREAD

**Issue by itJunky** [darkoperator/dnsrecon#70]
```
root@Hosting:~/src/dnsrecon# ./dnsrecon.py ya.ru
Traceback (most recent call last):
  File "./dnsrecon.py", line 54, in <module>
    import dns.message
ImportError: No module named dns.message
root@Hosting:~/src/dnsrecon# pip install --upgrade dns
Collecting dns
  Could not find a version that satisfies the requirement dns (from versions: )
No matching distribution found for dns
root@Hosting:~/src/dnsrecon# 

```

**Comment by darkoperator** [comment]
Did you installed dnspython module and other dependencies ?

**Comment by itJunky** [comment]
Thanks, i fix it by `pip install -r requirements.txt`
May be you write Installation section to README instead changelog?

**Comment by darkoperator** [comment]
There is one in the wiki

**Comment by itJunky** [comment]
https://github.com/darkoperator/dnsrecon/wiki/Installation-Instruction
It's empty

**Comment by darkoperator** [comment]
https://github.com/darkoperator/dnsrecon/wiki/Installation-Instructions works on my phone. Will later check what could the problem be. Im from PR and limited power and internet connection at the moment

**Comment by mazen160** [comment]
It should work now, the link was invalid.

**Comment by itJunky** [comment]
Doesn't work.
I see it(http://joxi.ru/xAeBOxVUYPq0Zr) by this URL https://github.com/darkoperator/dnsrecon/wiki/Installation-Instruction

**Comment by darkoperator** [comment]
Will fix in a month or so I will fix it when I have power and internet at home (Puerto Rico)
