### ISSUE TITLE
Zone transfer doesn't seems to work on dnsrcon v0.8.13

### ISSUE THREAD

**Issue by Ysagi** [darkoperator/dnsrecon#84]
Hi.

Thanks for a great project. The Zone transfer (AXFR) doesn't seem to work on Version: 0.8.13.

Version 0.8.13
$ dnsrecon.py -a -d DOMAIN
Get the error:
[*] Resolving SOA Record
[-] Could not obtain the domains SOA Record.

Doing the same thing on the same domain with Version 0.8.11
$ dnsrecon.py -a -d DOMAIN
Version: 0.8.11
[*] Resolving SOA Record
[+] 	 SOA ...

Best regards Ysagi

**Comment by trollmad3** [comment]
Are you running a proxy?

**Comment by darkoperator** [comment]
Sorry about the issue, my fault for not testing against a lab box before merging that PR. Will need to setup one to test it out and figure what the issue is.

**Comment by Ysagi** [comment]
Thanks for the update guys.

**Comment by darkoperator** [comment]
I believe the commit I just made should have fixed the issue, can you do a pull and test before I make a release?

**Comment by nurfed1** [comment]
It does seem to work now, thnx

**Comment by trollmad3** [comment]
@Ysagi Close the issue, it works now.
