### ISSUE TITLE
ds_zone_walk timeout error message conflicts with config options

### ISSUE THREAD

**Issue by tsellers-r7** [darkoperator/dnsrecon#97]
The following error message in `ds_zone_walk` indicates that a request to a server timed out **and** that the user can configure this time:

https://github.com/darkoperator/dnsrecon/blob/39847475801a1c0cfe0630ca00123ec2fc278934/dnsrecon.py#L1303-L1307

This value is actually not user configurable.  It is hard set to 3 seconds when the `res` object is recreated.

https://github.com/darkoperator/dnsrecon/blob/39847475801a1c0cfe0630ca00123ec2fc278934/dnsrecon.py#L1234-L1238

This is a straightforward fix and I can PR it if you'd let me know your preference for handling it:
1. This value uses the same value as `--lifetime`
1. This value uses a new value specified on the command line, for example `--lifetime-walk`
1. This value is not user configurable and the error message is updated.

**Comment by L1ghtn1ng** [comment]
This still the case with the code in master?

**Comment by tsellers-r7** [comment]
@L1ghtn1ng  - It appears so

https://github.com/darkoperator/dnsrecon/blob/054ad8028acd3ae39a16cf975525091a11c275c7/dnsrecon.py#L1215-L1216

**Comment by L1ghtn1ng** [comment]
@tsellers-r7 If you would like happy for you to do a PR and I can merge it

**Comment by L1ghtn1ng** [comment]
@tsellers-r7 Does this fix the issue for you? https://github.com/L1ghtn1ng/dnsrecon/commit/3b32cb619c11d8d476a84aa2e428c191a36784c6 if you want to test it please clone my fork and checkout my dev branch

**Comment by L1ghtn1ng** [comment]
been merged into master my fix

**Comment by tsellers-r7** [comment]
Sorry @L1ghtn1ng I lost track of this request.
