### ISSUE TITLE
New version 0.8.2 is lower than previous version 0.8.14

### ISSUE THREAD

**Issue by sbrun** [darkoperator/dnsrecon#98]
Hi,
I would like to update the package in Kali / Debian (https://bugs.kali.org/view.php?id=5365)
But you released a new version 0.8.2 a few days ago and the previous version was 0.8.14: 
0.8.2 is lower than 0.8.14.
Could you release a new version higher than 0.8.14, for example 0.8.20?

Thanks!

**Comment by tsellers-r7** [comment]
FYI @sbrun  - Carlos has addressed this issue by bumping the release version to 9.0 - https://github.com/darkoperator/dnsrecon/releases/tag/0.9.0

**Comment by sbrun** [comment]
Thanks!
